INSERT INTO dependencias (nombre, abreviatura, activo, origen_id)
VALUES ('Alcaldía', 'A', true, 2),
       ('Concejo Municipal', 'CM', true, 104),
       ('Gerencia de Desarrollo Ambiental', 'GDA', true, 57),
       ('Gerencia de Desarrollo Económico', 'GDE', true, 41),
       ('Gerencia de Desarrollo Social y Humano', 'GDSH', true, 136),
       ('Gerencia de Desarrollo Territorial y Urbano', 'GDTU', true, 125),
       ('Gerencia de Infraestructura Pública', 'GIP', true, 121),
       ('Gerencia de Seguridad Ciudadana', 'GSC', true, 61),
       ('Gerencia de Transportes y Seguridad Vial', 'GTSV', true, 128),
       ('Gerencia de Turismo y Cultura', 'GTC', true, 142),
       ('Gerencia Municipal', 'GM', true, 9),
       ('Oficina de Abastecimiento y Control Patrimonial', 'OACP', true, 114),
       ('Oficina de Contabilidad', 'OC', true, 115),
       ('Oficina de Mejor Atención al Ciudadano', 'OMAC', true, 110),
       ('Oficina de Planeamiento y Modernización', 'OPM', true, 118),
       ('Oficina de Presupuesto', 'OP', true, 119),
       ('Oficina de Programación Multianual de Inversiones', 'OPMI', true, 120),
       ('Oficina de Remuneraciones y Control de Personal', 'ORCP', true, 112),
       ('Oficina de Tecnologías de la Información', 'OTI', true, 117),
       ('Oficina de Tesorería', 'OT', true, 116),
       ('Oficina General de Administración y Finanzas', 'OGAF', true, 113),
       ('Oficina General de Asesoría Jurídica', 'OGAJ', true, 11),
       ('Oficina General de Gestión de Recursos Humanos', 'OGGRRHH', true, 24),
       ('Oficina General de Gestión Documentaria y Atención al Ciudadano', 'OGGDAC', true, 109),
       ('Oficina General de Imagen y Comunicaciones Institucionales', 'OGICI', true, 111),
       ('Oficina General de Planeamiento y Presupuesto', 'OGPP', true, 12),
       ('Procuraduría Pública', 'PP', true, 106),
       ('Subgerencia de Comercialización y Licencias', 'SCL', true, 132),
       ('Subgerencia de Educación Recreación y Deporte', 'SERD', true, 139),
       ('Subgerencia de Ejecución de Inversiones', 'SEI', true, 123),
       ('Subgerencia de Formulación de Inversiones', 'SFI', true, 122),
       ('Subgerencia de Gestión Ambiental', 'SGA', true, 133),
       ('Subgerencia de Gestión de Riesgo y Desastres', 'SGRD', true, 141),
       ('Subgerencia de Gestión Integral de Residuos Sólidos', 'SGIRS', true, 134),
       ('Subgerencia de Inspección y Seguridad Vial', 'SISV', true, 130),
       ('Subgerencia de Licencias y Permisos Urbanos ', 'SLPU', true, 127),
       ('Subgerencia de Mantenimiento y Gestión de Caminos', 'SMGC', true, 124),
       ('Subgerencia de Participación Vecinal y Registro Civil', 'SPVRC', true, 138),
       ('Subgerencia de Planificación Territorial y Centro Histórico', 'SPTCH', true, 126),
       ('Subgerencia de Productividad y Promoción de la Inversión', 'SPPI', true, 131),
       ('Subgerencia de Programas Sociales y Empadronamiento', 'SPSE', true, 137),
       ('Subgerencia de Regulación y Autorizaciones de Transporte', 'SRAT', true, 129),
       ('Subgerencia de Salud', 'SSA', true, 54),
       ('Subgerencia de Saneamiento Básico', 'SSB', true, 135),
       ('Subgerencia de Serenazgo', 'SSE', true, 140);
