INSERT INTO categoria_servicios (nombre)
VALUES ('Servicios de Estación de Trabajo'),
       ('Servicios de Comunicación'),
       ('Servicios de Conectividad'),
       ('Servicios de Acceso e Identidad'),
       ('Servicios de Almacenamiento y Archivos'),
       ('Servicios de Aplicaciones Institucionales'),
       ('Servicios de Digitalización y Documento Electrónico'),
       ('Servicios de Capacitación TI');

-- Servicios del catálogo
INSERT INTO servicios (id_categoria, nombre, tipo, requiere_aprobacion, tipo_aprobador, id_sla_defecto)
VALUES (1, 'Provisión de equipo de cómputo', 'solicitud', TRUE, 'ambos', 3),
       (1, 'Instalación o actualización de software', 'solicitud', FALSE, NULL, 3),
       (1, 'Reparación o reemplazo de equipo', 'solicitud', FALSE, NULL, 2),
       (1, 'Configuración de impresora o escáner', 'solicitud', FALSE, NULL, 4),
       (2, 'Creación de cuenta de correo institucional', 'solicitud', TRUE, 'supervisor_oti', 3),
       (2, 'Acceso a plataforma de videoconferencia', 'solicitud', FALSE, NULL, 4),
       (2, 'Acceso a directorio telefónico interno (VoIP)', 'solicitud', FALSE, NULL, 4),
       (2, 'Acceso a la intranet municipal', 'solicitud', FALSE, NULL, 4),
       (3, 'Acceso a internet', 'solicitud', FALSE, NULL, 3),
       (3, 'Acceso a la red institucional (LAN/WiFi)', 'solicitud', FALSE, NULL, 3),
       (3, 'Acceso remoto a la red (VPN)', 'solicitud', TRUE, 'supervisor_oti', 3),
       (4, 'Creación de cuenta de usuario', 'solicitud', TRUE, 'ambos', 2),
       (4, 'Restablecimiento de contraseña', 'solicitud', FALSE, NULL, 2),
       (4, 'Solicitud de acceso a sistema o aplicativo', 'solicitud', TRUE, 'jefe_area', 3),
       (4, 'Modificación o baja de cuenta de usuario', 'solicitud', TRUE, 'supervisor_oti', 2),
       (5, 'Almacenamiento compartido en red', 'solicitud', FALSE, NULL, 4),
       (5, 'Recuperación de archivos desde respaldo', 'solicitud', FALSE, NULL, 2),
       (5, 'Solicitud de espacio adicional de almacenamiento', 'solicitud', TRUE, 'jefe_area', 4),
       (6, 'Acceso al SIGA', 'solicitud', TRUE, 'ambos', 2),
       (6, 'Acceso al SIAF', 'solicitud', TRUE, 'ambos', 2),
       (6, 'Acceso al sistema de Trámite Documentario', 'solicitud', TRUE, 'jefe_area', 3),
       (6, 'Acceso al sistema de Planillas / RRHH', 'solicitud', TRUE, 'ambos', 2),
       (6, 'Acceso al sistema de Recaudación Tributaria', 'solicitud', TRUE, 'ambos', 2),
       (7, 'Digitalización de documentos físicos', 'solicitud', FALSE, NULL, 4),
       (7, 'Obtención de firma digital institucional', 'solicitud', TRUE, 'supervisor_oti', 3),
       (7, 'Soporte al expediente electrónico', 'solicitud', FALSE, NULL, 3),
       (8, 'Capacitación en ofimática', 'solicitud', FALSE, NULL, 4),
       (8, 'Capacitación en aplicativos institucionales', 'solicitud', FALSE, NULL, 4),
       (8, 'Inducción TI para personal nuevo', 'solicitud', TRUE, 'jefe_area', 3);
